-- Vance Brown E-Commerce Supabase Schema Setup Script
-- Open your new Supabase Project -> SQL Editor -> New Query -> Paste this script and click Run.

-- 1. CREATE CATEGORIES TABLE
CREATE TABLE IF NOT EXISTS public.categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. CREATE PRODUCTS TABLE
CREATE TABLE IF NOT EXISTS public.products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    price NUMERIC NOT NULL DEFAULT 0,
    image TEXT NOT NULL,
    description TEXT,
    "desc" TEXT, -- fallback column
    category_id BIGINT REFERENCES public.categories(id) ON DELETE SET NULL,
    sizes TEXT[] DEFAULT '{}',
    colors TEXT[] DEFAULT '{}',
    gallery TEXT[] DEFAULT '{}',
    is_top_pick BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. CREATE EMPLOYEES TABLE
CREATE TABLE IF NOT EXISTS public.employees (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    name TEXT NOT NULL,
    email TEXT NOT NULL UNIQUE,
    password TEXT NOT NULL,
    role TEXT DEFAULT 'employee', -- 'employee' or 'super_admin'
    balance NUMERIC DEFAULT 250,
    site TEXT DEFAULT '',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. CREATE ORDERS TABLE
CREATE TABLE IF NOT EXISTS public.orders (
    id TEXT PRIMARY KEY, -- e.g. 'ORD-1234'
    employee_id UUID REFERENCES public.employees(id) ON DELETE SET NULL,
    total_bucks NUMERIC NOT NULL,
    status TEXT DEFAULT 'Processing', -- 'Processing', 'Shipped', 'Delivered'
    items_count INT DEFAULT 1,
    details JSONB DEFAULT '{}', -- contains deliveryInfo and cart items array
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable RLS (Optional - you can disable or add policies if needed. For convenience, let's keep it simple)
ALTER TABLE public.categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.employees ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.orders ENABLE ROW LEVEL SECURITY;

-- Create public read/write access policies for simplicity in demo/testing
CREATE POLICY "Allow public read" ON public.categories FOR SELECT USING (true);
CREATE POLICY "Allow public insert" ON public.categories FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public update" ON public.categories FOR UPDATE USING (true);
CREATE POLICY "Allow public delete" ON public.categories FOR DELETE USING (true);

CREATE POLICY "Allow public read" ON public.products FOR SELECT USING (true);
CREATE POLICY "Allow public insert" ON public.products FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public update" ON public.products FOR UPDATE USING (true);
CREATE POLICY "Allow public delete" ON public.products FOR DELETE USING (true);

CREATE POLICY "Allow public read" ON public.employees FOR SELECT USING (true);
CREATE POLICY "Allow public insert" ON public.employees FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public update" ON public.employees FOR UPDATE USING (true);
CREATE POLICY "Allow public delete" ON public.employees FOR DELETE USING (true);

CREATE POLICY "Allow public read" ON public.orders FOR SELECT USING (true);
CREATE POLICY "Allow public insert" ON public.orders FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public update" ON public.orders FOR UPDATE USING (true);
CREATE POLICY "Allow public delete" ON public.orders FOR DELETE USING (true);

-- 5. SEED INITIAL DEPARTMENTS
INSERT INTO public.categories (name) VALUES 
('SHIRTS & POLOS'),
('SWEATSHIRTS'),
('TSHIRTS'),
('ACCESSORIES'),
('HATS')
ON CONFLICT (name) DO NOTHING;

-- 6. SEED INITIAL EMPLOYEES (VANCE BROWN THEMED)
-- Note: You can change passwords and emails here as you like.
INSERT INTO public.employees (name, email, password, role, balance, site) VALUES
('Vance Admin', 'admin@vancebrown.com', 'vance2026', 'super_admin', 250, 'HQ - Corporate Office'),
('Carlos Silva', 'carlos@vancebrown.com', 'vance2026', 'employee', 250, 'Site 42 - Main Hub'),
('Mike Ross', 'mike@vancebrown.com', 'vance2026', 'employee', 250, 'HQ - Corporate Office'),
('Sarah Connor', 'sarah@vancebrown.com', 'vance2026', 'employee', 250, 'Hub A - Northern District'),
('Shezi Dev', 'developer@vancebrown.com', 'vance2026', 'employee', 250, 'Site 42 - Main Hub')
ON CONFLICT (email) DO NOTHING;

-- 7. SEED INITIAL PRODUCTS
INSERT INTO public.products (title, price, image, description, "desc", category_id, sizes, colors, is_top_pick) 
SELECT 
    'Vance Brown Premium Polo', 
    45, 
    '/cat_polos.jpg', 
    'Breathable, moisture-wicking royal blue polo with embroidered company logo. Perfect for site visits.', 
    'Breathable, moisture-wicking royal blue polo with embroidered company logo. Perfect for site visits.',
    c.id, 
    ARRAY['S', 'M', 'L', 'XL'], 
    ARRAY['Blue', 'Black', 'White'], 
    true
FROM public.categories c WHERE c.name = 'SHIRTS & POLOS' LIMIT 1;

INSERT INTO public.products (title, price, image, description, "desc", category_id, sizes, colors, is_top_pick) 
SELECT 
    'Vance Brown Official Cap', 
    25, 
    '/wb_cap.jpg', 
    'Premium Vance Brown Builder corporate cap featuring embroidered company logo and adjustable fit.', 
    'Premium Vance Brown Builder corporate cap featuring embroidered company logo and adjustable fit.',
    c.id, 
    ARRAY['One Size'], 
    ARRAY['Navy', 'Black', 'Grey'], 
    true
FROM public.categories c WHERE c.name = 'HATS' LIMIT 1;

INSERT INTO public.products (title, price, image, description, "desc", category_id, sizes, colors, is_top_pick) 
SELECT 
    'Vance Brown Heavy-Duty Zip Jacket', 
    85, 
    '/jacket_wb_front.jpg', 
    'Warm and insulated dark workwear zip-jacket featuring premium Vance Brown embroidery. Designed to withstand cold weather on construction sites.', 
    'Warm and insulated dark workwear zip-jacket featuring premium Vance Brown embroidery. Designed to withstand cold weather on construction sites.',
    c.id, 
    ARRAY['M', 'L', 'XL', 'XXL'], 
    ARRAY['Grey', 'Black', 'Navy'], 
    true
FROM public.categories c WHERE c.name = 'SWEATSHIRTS' LIMIT 1;

INSERT INTO public.products (title, price, image, description, "desc", category_id, sizes, colors, gallery, is_top_pick) 
SELECT 
    'Vance Brown Logo T-Shirt', 
    30, 
    '/tshirt_wb_front.jpg', 
    'Premium heavy cotton t-shirt with Vance Brown logo printed on the front chest and corporate branding across the back.', 
    'Premium heavy cotton t-shirt with Vance Brown logo printed on the front chest and corporate branding across the back.',
    c.id, 
    ARRAY['S', 'M', 'L', 'XL', 'XXL'], 
    ARRAY['Black', 'White', 'Grey'], 
    ARRAY['/tshirt_wb_back.jpg'],
    true
FROM public.categories c WHERE c.name = 'TSHIRTS' LIMIT 1;
